### ISSUE TITLE
No filtra API oData

### ISSUE THREAD

**Issue by dvelasquez** [dmunozgaete/Karma-REST-Framework#1]
La siguiente consulta:

```
/Office/?$&limit=10&$filter=enterpriseToken eq 'f12587b0-8094-4995-ab7b-d598114aa63a'
```

Obtiene un error

```
{
  "error": "API005",
  "error_description": "El campo \"enterprisetoken\" filtrado por la clausula \"enterprisetoken\" no existe en el modelo consultado"
}
```

Error parece corresponder a la capa Karma que compara los nombres de las propiedades y discrimina por mayusculas/minusculas.

**Comment by dmunozgaete** [comment]
ya se encuentra corregido =), existía un problema de comparación de campos, de forma "case-sensitive" , pero en el código , por defecto siempre bajaba a minúsculas xD, para futuras referencias , seria recomendable utilizar , snake-case.

PD: Existe una función , que permite generar "hijos" de una vista compuesta por mas de una tabla relacionada. 

Ejemplo de salida de una vista compuesta por mas de una relación:

```
{ 
  name: 'Jhon Doe',
  email: 'dmunoz@valentys.com',
  contact:{
     linkedin: 'http://linkedin.com/jhondoe',
    facebook: 'facebook.com/jsjs'
 }
}
```

Para ello, se debe utilizar en la vista del modelo texto de acuerdo a la norma snake-case, y el parseador a json , reconocera que es una "hijo" del elemento padre ;) es decir , el nombre del campo seria: 

contact_linkedin y contact_facebook
