### ISSUE TITLE
Filtrar respuesta OData desde el controlador

### ISSUE THREAD

**Issue by dvelasquez** [dmunozgaete/Karma-REST-Framework#3]
Seria interesante una opcion para poder filtrar una respuesta OData desde el mismo controlador y no solamente desde la llamada a la API.

De esta manera podriamos filtrar una vista con datos fijos antes de devolverla a la api.

**Comment by dvelasquez** [comment]
Sugerencia:

Modificar el HttpQueryBuilder.cs para que soporte filtros adicionales.

**Comment by dmunozgaete** [comment]
Añadir Soporte en el constructor para un objeto KQL , donde se permita establecer una configuración base.

Archivo: [HttpQueryBuilder](https://github.com/dmunozgaete/Gale/blob/develop/REST/Queryable/OData/Builders/HttpQueryBuilder.cs)

**Comment by dmunozgaete** [comment]
Se añade soporte en milestone v2.2.5
[Release](https://github.com/dmunozgaete/Gale/releases/tag/v2.2.5)

#Ejemplo de Uso

``` csharp
        [HierarchicalRoute("/{type}")]
        public IHttpActionResult GetInspections(String type)
        {
            //---------------------------------------------------------------------------
            // Setting Static Values (Create a Base Gale Query Language Configuration)
            var config = new Gale.REST.Queryable.OData.Builders.GQLConfiguration();

            // Adding some Filter's ;)
            config.filters.Add(new Gale.REST.Queryable.OData.Builders.GQLConfiguration.Filter()
            {
                field = "type_identifier",
                operatorAlias = "eq",
                value = type
            });
            //---------------------------------------------------------------------------

            // Setup in the Queryable Endpoint
            return new Gale.REST.Http.HttpQueryableActionResult<Models.V_Document>(this.Request, config);
        }
```
